replicaCount: 1

image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  hostname: wordpress.local
  annotations: {}
  pathType: ImplementationSpecific
  path: /

resources: {}

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

mariadb:
  enabled: true
  rootPassword: pas$woRdd1
  user: use-user
  password: pas$woRdd1
  database: wordpress
